// Code generated by "stringer -type=ProxyErrorType"; DO NOT EDIT.

package lib

import "fmt"

const (
	_ProxyErrorType_name_0 = "ProxyGeneralErrProxyNotAllowed"
	_ProxyErrorType_name_1 = "ProxyConnectFailed"
	_ProxyErrorType_name_2 = "ProxyCmdUnsupportedProxyAddrUnsupported"
)

var (
	_ProxyErrorType_index_0 = [...]uint8{0, 15, 30}
	_ProxyErrorType_index_1 = [...]uint8{0, 18}
	_ProxyErrorType_index_2 = [...]uint8{0, 19, 39}
)

func (i ProxyErrorType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ProxyErrorType_name_0[_ProxyErrorType_index_0[i]:_ProxyErrorType_index_0[i+1]]
	case i == 5:
		return _ProxyErrorType_name_1
	case 7 <= i && i <= 8:
		i -= 7
		return _ProxyErrorType_name_2[_ProxyErrorType_index_2[i]:_ProxyErrorType_index_2[i+1]]
	default:
		return fmt.Sprintf("ProxyErrorType(%d)", i)
	}
}
